language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -q err pytest pytest-pep8 --use-wheel
  - pip install -q coverage coveralls --use-wheel

# command to run tests
script:
 - pep8 --statistics --show-source mycroft.py
 - coverage run --source mycroft -m py.test

after_success:
  coveralls
